name: Java FSD_BE

on:
  push:
    branches:
      - "develop"
      - "**"
  pull_request:
    branches:
      - "develop"

jobs:
  build_test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: ifarm
          POSTGRES_USER: ${DATABASE_USERNAME}
          POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
        ports:
          - 5432:5432
        options: >- # Health check to ensure PostgreSQL is ready
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/ifarm
      SPRING_DATASOURCE_USERNAME: ${DATABASE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DATABASE_PASSWORD}

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h localhost -p 5432 -U ${DATABASE_USERNAME}; do
            echo "Waiting for PostgreSQL..."
            sleep 2
          done

      - name: Build with Maven
        run: mvn -B package --file pom.xml

  publish-job:
    runs-on: ubuntu-latest
    needs: build_test

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: ifarm
          POSTGRES_USER: ${DATABASE_USERNAME}
          POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env: #
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/ifarm
      SPRING_DATASOURCE_USERNAME: ${DATABASE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DATABASE_PASSWORD}

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h localhost -p 5432 -U ${DATABASE_USERNAME}; do
            echo "Waiting for PostgreSQL..."
            sleep 2
          done

      - run: mvn --batch-mode --update-snapshots verify
      - run: mkdir staging && cp target/*.jar staging

      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging
